services:

  bot:
    volumes:
      - ./bot:/usr/src/app
    # environment:
    #   - SOCKS_HOST=tor
    # depends_on:
    #   - tor

  # tor:
  #   image: dperson/torproxy

  webapp:
    restart: unless-stopped
    build: ./webapp

  postgres:
    ports:
      - '5437:5432'
