version: '3'
services:

  bot:
    restart: always
    build: ./bot
    environment:
    - PGHOST=postgres
    - PGUSER=postgres
    depends_on:
    - postgres
    - flyway

  postgres:
    restart: always
    image: postgres:11
    volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  flyway:
    image: boxfuse/flyway:5
    command: -url=jdbc:postgresql://postgres/postgres -user=postgres -connectRetries=60 -baselineOnMigrate=true migrate
    volumes:
    - ./flyway/sql:/flyway/sql
    depends_on:
    - postgres
